build-all: Report errors at the end of output
Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>

diff --git a/build-all b/build-all
--- a/build-all
+++ b/build-all
@@ -1,13 +1,23 @@
-#!/bin/bash -x
+#!/bin/bash
 set -e
 
 mydir="$(dirname "$0")"
 export BUILD_ARGS=("$@")
 
+export ERRORS=
+
 B() {
 	local name="$1"
 	shift
-	(cd "$name" && make "${BUILD_ARGS[@]}" || echo "Build of ${name} failed" >&2 ; )
+	if ! ( cd "$name" && make "${BUILD_ARGS[@]}"; );then
+		echo "Build of ${name} failed" >&2
+		ERRORS=1
+	fi
 }
 
 source "$mydir/build-names"
+
+if [ -n "$ERRORS" ];then
+	echo ERRORS ABOVE >&2
+	exit 1
+fi
