show error details
Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>

diff --git a/configure-all b/configure-all
--- a/configure-all
+++ b/configure-all
@@ -7,7 +7,15 @@ B() {
 	local name="$1"
 	shift
 	mkdir -p "$name"
-	(cd "$name" && ../configure "$@"; ) || exit
+	if ! ( cd "$name" && ../configure "$@"; );then
+		echo "ERROR: Configure of ${name} failed" >&2
+		ERRORS="$ERRORS ${name}"
+	fi
 }
 
 source "$mydir/build-names"
+
+if [ -n "$ERRORS" ];then
+	echo ERRORS ABOVE: $ERRORS >&2
+	exit 1
+fi
